// State data with pay rates and info
const states = {
    'alabama': { name: 'Alabama', code: 'AL', population: '5.1M', centers: '60+', payRange: '$45-$80', cities: ['Birmingham', 'Mobile', 'Huntsville', 'Montgomery', 'Tuscaloosa'] },
    'alaska': { name: 'Alaska', code: 'AK', population: '736K', centers: '15+', payRange: '$50-$85', cities: ['Anchorage', 'Fairbanks', 'Juneau', 'Sitka', 'Wasilla'] },
    'arizona': { name: 'Arizona', code: 'AZ', population: '7.5M', centers: '80+', payRange: '$45-$85', cities: ['Phoenix', 'Tucson', 'Mesa', 'Chandler', 'Scottsdale'] },
    'arkansas': { name: 'Arkansas', code: 'AR', population: '3.0M', centers: '40+', payRange: '$40-$75', cities: ['Little Rock', 'Fort Smith', 'Fayetteville', 'Springdale', 'Jonesboro'] },
    'california': { name: 'California', code: 'CA', population: '39.2M', centers: '200+', payRange: '$50-$90', cities: ['Los Angeles', 'San Francisco', 'San Diego', 'Sacramento', 'Fresno'] },
    'colorado': { name: 'Colorado', code: 'CO', population: '5.8M', centers: '70+', payRange: '$45-$85', cities: ['Denver', 'Colorado Springs', 'Aurora', 'Fort Collins', 'Lakewood'] },
    'connecticut': { name: 'Connecticut', code: 'CT', population: '3.6M', centers: '30+', payRange: '$45-$80', cities: ['Hartford', 'New Haven', 'Stamford', 'Bridgeport', 'Waterbury'] },
    'delaware': { name: 'Delaware', code: 'DE', population: '1.0M', centers: '15+', payRange: '$45-$75', cities: ['Wilmington', 'Dover', 'Newark', 'Middletown', 'Smyrna'] },
    'florida': { name: 'Florida', code: 'FL', population: '22.6M', centers: '150+', payRange: '$45-$85', cities: ['Miami', 'Orlando', 'Tampa', 'Jacksonville', 'St. Petersburg'] },
    'georgia': { name: 'Georgia', code: 'GA', population: '10.8M', centers: '90+', payRange: '$45-$80', cities: ['Atlanta', 'Augusta', 'Columbus', 'Savannah', 'Macon'] },
    'hawaii': { name: 'Hawaii', code: 'HI', population: '1.4M', centers: '20+', payRange: '$50-$85', cities: ['Honolulu', 'Hilo', 'Kailua', 'Kaneohe', 'Pearl City'] },
    'idaho': { name: 'Idaho', code: 'ID', population: '1.9M', centers: '25+', payRange: '$40-$75', cities: ['Boise', 'Meridian', 'Nampa', 'Idaho Falls', 'Pocatello'] },
    'illinois': { name: 'Illinois', code: 'IL', population: '12.6M', centers: '100+', payRange: '$45-$85', cities: ['Chicago', 'Aurora', 'Peoria', 'Rockford', 'Springfield'] },
    'indiana': { name: 'Indiana', code: 'IN', population: '6.8M', centers: '70+', payRange: '$45-$80', cities: ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend', 'Carmel'] },
    'iowa': { name: 'Iowa', code: 'IA', population: '3.2M', centers: '35+', payRange: '$40-$75', cities: ['Des Moines', 'Cedar Rapids', 'Davenport', 'Sioux City', 'Waterloo'] },
    'kansas': { name: 'Kansas', code: 'KS', population: '2.9M', centers: '40+', payRange: '$40-$75', cities: ['Wichita', 'Overland Park', 'Kansas City', 'Topeka', 'Olathe'] },
    'kentucky': { name: 'Kentucky', code: 'KY', population: '4.5M', centers: '50+', payRange: '$40-$75', cities: ['Louisville', 'Lexington', 'Bowling Green', 'Owensboro', 'Covington'] },
    'louisiana': { name: 'Louisiana', code: 'LA', population: '4.6M', centers: '50+', payRange: '$45-$80', cities: ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette', 'Lake Charles'] },
    'maine': { name: 'Maine', code: 'ME', population: '1.4M', centers: '20+', payRange: '$45-$75', cities: ['Portland', 'Lewiston', 'Bangor', 'South Portland', 'Auburn'] },
    'maryland': { name: 'Maryland', code: 'MD', population: '6.2M', centers: '60+', payRange: '$45-$85', cities: ['Baltimore', 'Frederick', 'Rockville', 'Gaithersburg', 'Bowie'] },
    'massachusetts': { name: 'Massachusetts', code: 'MA', population: '7.0M', centers: '70+', payRange: '$50-$85', cities: ['Boston', 'Worcester', 'Springfield', 'Cambridge', 'Lowell'] },
    'michigan': { name: 'Michigan', code: 'MI', population: '10.0M', centers: '90+', payRange: '$45-$80', cities: ['Detroit', 'Grand Rapids', 'Warren', 'Sterling Heights', 'Lansing'] },
    'minnesota': { name: 'Minnesota', code: 'MN', population: '5.7M', centers: '60+', payRange: '$45-$80', cities: ['Minneapolis', 'St. Paul', 'Rochester', 'Duluth', 'Bloomington'] },
    'mississippi': { name: 'Mississippi', code: 'MS', population: '2.9M', centers: '35+', payRange: '$40-$75', cities: ['Jackson', 'Gulfport', 'Southaven', 'Hattiesburg', 'Biloxi'] },
    'missouri': { name: 'Missouri', code: 'MO', population: '6.2M', centers: '70+', payRange: '$45-$80', cities: ['Kansas City', 'St. Louis', 'Springfield', 'Columbia', 'Independence'] },
    'montana': { name: 'Montana', code: 'MT', population: '1.1M', centers: '15+', payRange: '$40-$75', cities: ['Billings', 'Missoula', 'Great Falls', 'Bozeman', 'Helena'] },
    'nebraska': { name: 'Nebraska', code: 'NE', population: '2.0M', centers: '25+', payRange: '$40-$75', cities: ['Omaha', 'Lincoln', 'Bellevue', 'Grand Island', 'Kearney'] },
    'nevada': { name: 'Nevada', code: 'NV', population: '3.2M', centers: '40+', payRange: '$45-$85', cities: ['Las Vegas', 'Henderson', 'Reno', 'North Las Vegas', 'Sparks'] },
    'new-hampshire': { name: 'New Hampshire', code: 'NH', population: '1.4M', centers: '20+', payRange: '$45-$80', cities: ['Manchester', 'Nashua', 'Concord', 'Derry', 'Rochester'] },
    'new-jersey': { name: 'New Jersey', code: 'NJ', population: '9.3M', centers: '80+', payRange: '$45-$85', cities: ['Newark', 'Jersey City', 'Paterson', 'Elizabeth', 'Edison'] },
    'new-mexico': { name: 'New Mexico', code: 'NM', population: '2.1M', centers: '25+', payRange: '$40-$75', cities: ['Albuquerque', 'Las Cruces', 'Rio Rancho', 'Santa Fe', 'Roswell'] },
    'new-york': { name: 'New York', code: 'NY', population: '19.9M', centers: '120+', payRange: '$50-$90', cities: ['New York City', 'Buffalo', 'Rochester', 'Yonkers', 'Syracuse'] },
    'north-carolina': { name: 'North Carolina', code: 'NC', population: '10.7M', centers: '90+', payRange: '$45-$80', cities: ['Charlotte', 'Raleigh', 'Greensboro', 'Durham', 'Winston-Salem'] },
    'north-dakota': { name: 'North Dakota', code: 'ND', population: '779K', centers: '15+', payRange: '$40-$75', cities: ['Fargo', 'Bismarck', 'Grand Forks', 'Minot', 'West Fargo'] },
    'ohio': { name: 'Ohio', code: 'OH', population: '11.8M', centers: '100+', payRange: '$45-$80', cities: ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Akron'] },
    'oklahoma': { name: 'Oklahoma', code: 'OK', population: '4.0M', centers: '45+', payRange: '$40-$75', cities: ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow', 'Lawton'] },
    'oregon': { name: 'Oregon', code: 'OR', population: '4.3M', centers: '50+', payRange: '$45-$85', cities: ['Portland', 'Eugene', 'Salem', 'Gresham', 'Hillsboro'] },
    'pennsylvania': { name: 'Pennsylvania', code: 'PA', population: '13.0M', centers: '110+', payRange: '$45-$85', cities: ['Philadelphia', 'Pittsburgh', 'Allentown', 'Erie', 'Reading'] },
    'rhode-island': { name: 'Rhode Island', code: 'RI', population: '1.1M', centers: '15+', payRange: '$45-$80', cities: ['Providence', 'Warwick', 'Cranston', 'Pawtucket', 'East Providence'] },
    'south-carolina': { name: 'South Carolina', code: 'SC', population: '5.4M', centers: '55+', payRange: '$40-$75', cities: ['Charleston', 'Columbia', 'North Charleston', 'Mount Pleasant', 'Rock Hill'] },
    'south-dakota': { name: 'South Dakota', code: 'SD', population: '895K', centers: '15+', payRange: '$40-$75', cities: ['Sioux Falls', 'Rapid City', 'Aberdeen', 'Brookings', 'Watertown'] },
    'tennessee': { name: 'Tennessee', code: 'TN', population: '7.1M', centers: '70+', payRange: '$45-$80', cities: ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga', 'Clarksville'] },
    'texas': { name: 'Texas', code: 'TX', population: '30.5M', centers: '200+', payRange: '$50-$90', cities: ['Houston', 'Dallas', 'San Antonio', 'Austin', 'Fort Worth'] },
    'utah': { name: 'Utah', code: 'UT', population: '3.4M', centers: '40+', payRange: '$45-$80', cities: ['Salt Lake City', 'West Valley City', 'Provo', 'West Jordan', 'Orem'] },
    'vermont': { name: 'Vermont', code: 'VT', population: '647K', centers: '10+', payRange: '$45-$75', cities: ['Burlington', 'South Burlington', 'Rutland', 'Colchester', 'Essex'] },
    'virginia': { name: 'Virginia', code: 'VA', population: '8.7M', centers: '80+', payRange: '$45-$85', cities: ['Virginia Beach', 'Norfolk', 'Richmond', 'Newport News', 'Alexandria'] },
    'washington': { name: 'Washington', code: 'WA', population: '7.8M', centers: '80+', payRange: '$50-$90', cities: ['Seattle', 'Spokane', 'Tacoma', 'Vancouver', 'Bellevue'] },
    'west-virginia': { name: 'West Virginia', code: 'WV', population: '1.8M', centers: '20+', payRange: '$40-$70', cities: ['Charleston', 'Huntington', 'Morgantown', 'Parkersburg', 'Wheeling'] },
    'wisconsin': { name: 'Wisconsin', code: 'WI', population: '5.9M', centers: '60+', payRange: '$45-$80', cities: ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha', 'Racine'] },
    'wyoming': { name: 'Wyoming', code: 'WY', population: '578K', centers: '10+', payRange: '$40-$75', cities: ['Cheyenne', 'Casper', 'Laramie', 'Gillette', 'Rock Springs'] }
};

console.log('State data loaded:', Object.keys(states).length, 'states');